# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_conversions_pattern_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversions',
            name='pattern_input',
        ),
    ]
