# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0003_remove_conversions_pattern_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversions',
            name='pattern_input',
            field=models.TextField(default='atcg'),
        ),
    ]
