# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0005_remove_conversions_pattern_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversions',
            name='pattern_input',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
