# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0009_conversions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='conversions',
        ),
    ]
